spring.application.name=manage-product

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/productdb
spring.datasource.username=kane_user
spring.datasource.password=kane
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
